version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: user-service-gb1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s  # Increased start period
    networks:
      - kodinggo

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - kodinggo

  jetstream:
    image: nats
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      - NATS_ENABLE_JETSTREAM=true
    healthcheck:
      test: ["CMD-SHELL", "nats --server=nats://localhost:4222 stream list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - kodinggo
  
  server:
    build: .
    ports:
      - "8080:3200"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      jetstream:
        condition: service_started
    command: go run main.go httpsrv
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=user-service-gb1
    networks:
      - kodinggo

networks:
  kodinggo:
    driver: bridge
