// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pb/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JWTValidator_ValidateToken_FullMethodName = "/pb.JWTValidator/ValidateToken"
)

// JWTValidatorClient is the client API for JWTValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JWTValidatorClient interface {
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type jWTValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewJWTValidatorClient(cc grpc.ClientConnInterface) JWTValidatorClient {
	return &jWTValidatorClient{cc}
}

func (c *jWTValidatorClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, JWTValidator_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JWTValidatorServer is the server API for JWTValidator service.
// All implementations must embed UnimplementedJWTValidatorServer
// for forward compatibility.
type JWTValidatorServer interface {
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedJWTValidatorServer()
}

// UnimplementedJWTValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJWTValidatorServer struct{}

func (UnimplementedJWTValidatorServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedJWTValidatorServer) mustEmbedUnimplementedJWTValidatorServer() {}
func (UnimplementedJWTValidatorServer) testEmbeddedByValue()                      {}

// UnsafeJWTValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JWTValidatorServer will
// result in compilation errors.
type UnsafeJWTValidatorServer interface {
	mustEmbedUnimplementedJWTValidatorServer()
}

func RegisterJWTValidatorServer(s grpc.ServiceRegistrar, srv JWTValidatorServer) {
	// If the following call pancis, it indicates UnimplementedJWTValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JWTValidator_ServiceDesc, srv)
}

func _JWTValidator_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTValidatorServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JWTValidator_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTValidatorServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JWTValidator_ServiceDesc is the grpc.ServiceDesc for JWTValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JWTValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.JWTValidator",
	HandlerType: (*JWTValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _JWTValidator_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth/auth.proto",
}
